---
# tasks file for kaa_own_role
  - name: run the kaa_create_file module
    kaa.kaa_collection.kaa_my_own_module:
      name: "{{ name }}"
      path: "{{ path }}"
      content: "{{ content }}"
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'